apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "letsencrypt"
spec:
  acme:
    server: {{- if .Values.useStaging }} "https://acme-staging-v02.api.letsencrypt.org/directory" {{- else }} "https://acme-v02.api.letsencrypt.org/directory" {{- end }}
    email: {{ .Values.acmeEmail }}

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: "letsencrypt"

    solvers:
    # ACME DNS-01 provider configurations
    - dns01:
        cloudDNS:
          project: "terriajs"