name: PROD Cluster status

on:
  workflow_dispatch:

env:
  CLUSTER_NAME: search-data-gov-au-new
  CLUSTER_ZONE: australia-southeast1
  GCP_PROJECT: terriajs
  RELEASE_NAME: magda
  DEPLOY_NAMESPACE: dga-prod
  GCP_SRV_ACC_NAME: sa-githubactions-dga@terriajs.iam.gserviceaccount.com
  GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}

jobs:
  get-prod-cluster-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install gke-gcloud-auth-plugin
        run: |
          REPO_URL="https://packages.cloud.google.com/apt"
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] $REPO_URL cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          sudo curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

          sudo apt-get update -y
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Login to Cluster
        run: |
          echo $GCLOUD_KEY > ./gcloud-key.json
          gcloud auth activate-service-account ${GCP_SRV_ACC_NAME} --key-file=./gcloud-key.json
          gcloud container clusters get-credentials \
            ${CLUSTER_NAME} \
            --zone ${CLUSTER_ZONE} \
            --project ${GCP_PROJECT}
      
      - name: retrieve helm release history
        run: |
          echo "Retrieving helm release history...."
          helm history --namespace ${DEPLOY_NAMESPACE} ${RELEASE_NAME} --max 20

      - name: retrieve helm release config values
        run: |
          echo "Retrieving helm release config values...."
          helm get values --namespace ${DEPLOY_NAMESPACE} ${RELEASE_NAME} -a



